### ISSUE TITLE
FYI fails to compile on HEAD from phoenix_live_view

### ISSUE THREAD

**Issue by jsmestad** [petalframework/petal_components#42]
I have been running on `0.18.0-dev` of phoenix_live_view (commit `e24527536890be2f0565c4a6d122a89e819df58e` and later) for the bug fixes to the heex formatter. Obviously this is a pre-release commit, but I wanted to let you know that petal_components fails to compile.

```bash
❯ mix deps.compile petal_components
==> petal_components
Compiling 25 files (.ex)

== Compilation error in file lib/petal_components/modal.ex ==
** (CompileError) lib/petal_components/modal.ex:77: cannot find or invoke local \\/2 inside match. Only macros can be invoked in a match and they must be defined before their invocation. Called as: js \\ %JS{}
    (phoenix_live_view 0.18.0-dev) expanding macro: Phoenix.Component.__pattern__!/2
    lib/petal_components/modal.ex:77: PetalComponents.Modal.hide_modal/1
could not compile dependency :petal_components, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile petal_components", update it with "mix deps.update petal_components" or clean it with "mix deps.clean petal_components"
```

Everything works fine on `0.17.9` assuming once you downgrade you run `mix deps.compile phoenix_live_view` first.

**Comment by jsmestad** [comment]
Not entirely sure why this error happens, but I was able to get it running by adding a second method:

```elixir
  def hide_modal, do: hide_modal(%JS{})
  def hide_modal(js) do
    # ...
  end

  def show_modal, do: show_modal(%JS{})
  def show_modal(js) do
   # ...
  end
```

**Comment by mplatts** [comment]
Thanks for pointing this out and finding a fix. It seems like v0.18 has a bunch of new changes - I tried in Petal Pro and it wouldn't compile because it didn't like Alpine's `:class` attribute (`<div :class="">`). Will have to have a play around with it.

**Comment by jsmestad** [comment]
Yeah you can fix those by using x-bind:class

I think it has to do with the new :let and :for features in 0.17.10

**Comment by doughsay** [comment]
They've also now introduced a `<link ...>` function component which also conflicts.  I get this error when upgrading live view to latest HEAD:

```
== Compilation error in file lib/petal_components/button.ex ==
** (CompileError) lib/petal_components/button.ex:34: function link/1 imported from both PetalComponents.Link and Phoenix.LiveView.Helpers, call is ambiguous
    (phoenix_live_view 0.18.0-dev) expanding macro: Phoenix.LiveView.Helpers.sigil_H/2
    lib/petal_components/button.ex:33: PetalComponents.Button.button/1
```

**Comment by dvic** [comment]
#45 fixes the `link` issue, but I have not encountered the issue with `modal`, not sure if this is already fixed.
